CareStream.Web/Pages/Groups/CreateGroup.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using CareStream.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;

namespace CareStream.Web.Pages.Groups
{
    public class CreateGroupModel : PageModel
    {
        [BindProperty]
        public GroupModel groupModel { get; set; }

        public CreateGroupModel()
        {
            groupModel = new GroupModel();
        }
        public void OnGet()
        {
            try
            {
                if(groupModel.GroupTypes != null)
                {
                    var groupItems = new SelectList(new List<SelectListItem>());

                    var itemList = new List<SelectListItem>();
                    foreach (var groupType in groupModel.GroupTypes)
                    {
                        try
                        {
                            var groupTypeListItem = new SelectListItem
                            {
                                Text = groupType,
                                Value = groupType
                            };

                            itemList.Add(groupTypeListItem);
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine("Error while assign user group type for key {0}", groupType);
                            Console.WriteLine(ex);
                        }
                    }

                    groupItems = new SelectList(itemList, "Value", "Text");
                    ViewData["GroupType"] = groupItems;
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Expection occured while getting group type details");
                Console.WriteLine(ex);
            }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            GroupModel newGroupModel = null;
            try
            {

                if(groupModel != null)
                {
                    if (string.IsNullOrEmpty(groupModel.DisplayName) && string.IsNullOrEmpty(groupModel.GroupType))
                    {
                        return RedirectToPage("./Index");
                    }

                    switch (groupModel.GroupType)
                    {
                        case CareStreamConst.O365:
                            groupModel.GroupTypes = new List<string>
                            {
                                CareStreamConst.Unified
                            };
                            groupModel.MailEnabled = true;
                            groupModel.SecurityEnabled = false;
                            break;
                        case CareStreamConst.Security:
                            groupModel.GroupTypes = new List<string>();
                            groupModel.MailEnabled = false;
                            groupModel.SecurityEnabled = true;
                            break;
                    }
                    groupModel.Visibility = "Public";

                    var displayNames = Regex.Split(groupModel.DisplayName, @"\W+");

                    if (displayNames.Count() > 0)
                        groupModel.MailNickname = string.Join('_', displayNames);

                    HttpClient httpClient = new HttpClient();
                    httpClient.BaseAddress = new Uri(CareStreamConst.Base_Url);

                    var payload = JsonConvert.SerializeObject(groupModel);
                    StringContent content = new StringContent(payload, Encoding.UTF8, CareStreamConst.Application_Json);
                    var result = await httpClient.PostAsync($"{CareStreamConst.Base_API}{CareStreamConst.Group_Url}", content);

                    if (result.IsSuccessStatusCode)
                    {
                        var data = await result.Content.ReadAsStringAsync();
                        newGroupModel = JsonConvert.DeserializeObject<GroupModel>(data);
                    }

                    if (newGroupModel != null)
                    {
                        return RedirectToPage("./ViewGroup", new { id = newGroupModel.ObjectId });
                    }
                }
            }
            catch (Exception ex)
            {

                throw ex;
            }

            return RedirectToPage("./Index");
        }
    }
}

CareStream.Web/Pages/Groups/GroupMembers/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using CareStream.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace CareStream.Web.Pages.Groups.GroupMembers
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        [BindProperty]
        public GroupMemberModel groupMemberModel { get; set; }

        [BindProperty]
        GroupMemberAssignModel groupMemberAssignModel { get; set; }

        [BindProperty]
        public string GroupId { get; set; }

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public async Task OnGetAsync(string Id)
        {
            try
            {
                if (string.IsNullOrEmpty(Id))
                {
                    
                    Id = GetGroupIdFromQuery("controller");
                    if (string.IsNullOrEmpty(Id))
                             return;
                }
                
                TempData[CareStreamConst.Member_GroupId] = Id;
                GroupId = Id;
                HttpClient httpClient = new HttpClient();

                var httpResponse = await httpClient
                            .GetAsync($"{CareStreamConst.Base_Url}{CareStreamConst.Base_API}{CareStreamConst.GroupMember_By_Id_Url}{Id}");

                if (httpResponse.IsSuccessStatusCode)
                {
                    var data = await httpResponse.Content.ReadAsStringAsync();
                    groupMemberModel = JsonConvert.DeserializeObject<GroupMemberModel>(data);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        private string GetGroupIdFromQuery(string key)
        {
            var retVal = string.Empty;
            try
            {
                var id = TempData[CareStreamConst.Member_GroupId];
                if(id != null)
                {
                    return id.ToString();
                }

                if (Request.Query != null)
                {
                    if (Request.Query.Any())
                    {
                        if (Request.Query.ContainsKey(key))
                        {
                            retVal = Request.Query[key];
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }

            return retVal;
        }

        public async Task<IActionResult> OnPostAddMember(List<string> selectedMember)
        {
            var id = string.Empty;
            try
            {
                id = GetGroupIdFromQuery("id");

                if (selectedMember != null)
                {
                    if (selectedMember.Any() && !string.IsNullOrEmpty(id))
                    {
                        groupMemberAssignModel = new GroupMemberAssignModel();
                        groupMemberAssignModel.GroupId = id;
                        groupMemberAssignModel.SelectedMembers = selectedMember;


                        HttpClient httpClient = new HttpClient();
                        httpClient.BaseAddress = new Uri(CareStreamConst.Base_Url);

                        var payload = JsonConvert.SerializeObject(groupMemberAssignModel);
                        StringContent content = new StringContent(payload, Encoding.UTF8, CareStreamConst.Application_Json);
                        var result = await httpClient.PostAsync($"{CareStreamConst.Base_API}{CareStreamConst.GroupMember_Url}", content);

                        if (result.IsSuccessStatusCode)
                        {
                            var data = await result.Content.ReadAsStringAsync();
                        }
                    }
                }
               
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
            return this.RedirectToAction("OnGetAsync", id);
        }

        public async Task<ActionResult> OnPostGroupMemberDelete([FromBody] GroupMemberAssignModel groupMemberAssign)
        {
            try
            {
                if (groupMemberAssign != null)
                {

                    if (groupMemberAssign.SelectedMembers != null)
                    {
                        if (groupMemberAssign.SelectedMembers.Any() && !string.IsNullOrEmpty(groupMemberAssign.GroupId))
                        {
                            HttpClient httpClient = new HttpClient();
                            var url = $"{CareStreamConst.Base_Url}{CareStreamConst.Base_API}{CareStreamConst.GroupMember_Url}";

                            httpClient.BaseAddress = new Uri(CareStreamConst.Base_Url);
                            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Delete, new Uri(url));

                            var payload = JsonConvert.SerializeObject(groupMemberAssign);
                            request.Content = new StringContent(payload, Encoding.UTF8, CareStreamConst.Application_Json);
                            var result = await httpClient.SendAsync(request);

                            if (result.IsSuccessStatusCode)
                            {
                                var data = await result.Content.ReadAsStringAsync();
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
            return this.RedirectToAction("OnGetAsync");
        }
    }
}

CareStream.Web/Pages/Groups/GroupOwners/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using CareStream.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace CareStream.Web.Pages.Groups.GroupOwners
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        [BindProperty]
        public GroupOwnerModel groupOwnerModel { get; set; }

        [BindProperty]
        GroupOwnerAssignModel groupOwnerAssignModel { get; set; }

        [BindProperty]
        public string GroupId { get; set; }

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public async Task OnGetAsync(string Id)
        {
            try
            {
                if (string.IsNullOrEmpty(Id))
                {

                    Id = GetGroupIdFromQuery("controller");
                    if (string.IsNullOrEmpty(Id))
                        return;
                }

                TempData[CareStreamConst.Owner_GroupId] = Id;
                GroupId = Id;
                HttpClient httpClient = new HttpClient();

                var httpResponse = await httpClient
                            .GetAsync($"{CareStreamConst.Base_Url}{CareStreamConst.Base_API}{CareStreamConst.GroupOwner_By_Id_Url}{Id}");

                if (httpResponse.IsSuccessStatusCode)
                {
                    var data = await httpResponse.Content.ReadAsStringAsync();
                    groupOwnerModel = JsonConvert.DeserializeObject<GroupOwnerModel>(data);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        private string GetGroupIdFromQuery(string key)
        {
            var retVal = string.Empty;
            try
            {
                var id = TempData[CareStreamConst.Owner_GroupId];
                if (id != null)
                {
                    return id.ToString();
                }

                if (Request.Query != null)
                {
                    if (Request.Query.Any())
                    {
                        if (Request.Query.ContainsKey(key))
                        {
                            retVal = Request.Query[key];
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }

            return retVal;
        }

        public async Task<IActionResult> OnPostAddOwner(List<string> selectedOwner)
        {
            var id = string.Empty;
            try
            {
                id = GetGroupIdFromQuery("id");

                if (selectedOwner != null)
                {
                    if (selectedOwner.Any() && !string.IsNullOrEmpty(id))
                    {
                        groupOwnerAssignModel = new GroupOwnerAssignModel();
                        groupOwnerAssignModel.GroupId = id;
                        groupOwnerAssignModel.SelectedOwners = selectedOwner;


                        HttpClient httpClient = new HttpClient();
                        httpClient.BaseAddress = new Uri(CareStreamConst.Base_Url);

                        var payload = JsonConvert.SerializeObject(groupOwnerAssignModel);
                        StringContent content = new StringContent(payload, Encoding.UTF8, CareStreamConst.Application_Json);

                        var result = await httpClient.PostAsync($"{CareStreamConst.Base_API}{CareStreamConst.GroupOwner_Url}", content);

                        if (result.IsSuccessStatusCode)
                        {
                            var data = await result.Content.ReadAsStringAsync();
                        }
                    }
                }

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
            return this.RedirectToAction("OnGetAsync", id);
        }

        public async Task<ActionResult> OnPostGroupOwnerDelete([FromBody] GroupOwnerAssignModel groupOwnerAssign)
        {
            try
            {
                if (groupOwnerAssign != null)
                {

                    if (groupOwnerAssign.SelectedOwners != null)
                    {
                        if (groupOwnerAssign.SelectedOwners.Any() && !string.IsNullOrEmpty(groupOwnerAssign.GroupId))
                        {
                            HttpClient httpClient = new HttpClient();
                            var url = $"{CareStreamConst.Base_Url}{CareStreamConst.Base_API}{CareStreamConst.GroupOwner_Url}";

                            httpClient.BaseAddress = new Uri(CareStreamConst.Base_Url);
                            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Delete, new Uri(url));

                            var payload = JsonConvert.SerializeObject(groupOwnerAssign);
                            request.Content = new StringContent(payload, Encoding.UTF8, CareStreamConst.Application_Json);
                            var result = await httpClient.SendAsync(request);

                            if (result.IsSuccessStatusCode)
                            {
                                var data = await result.Content.ReadAsStringAsync();
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
            return this.RedirectToAction("OnGetAsync");
        }
    }
}

CareStream.Web/Pages/Groups/ViewGroup.cshtml.cs
using System.Net.Http;
using System.Threading.Tasks;
using CareStream.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace CareStream.Web.Pages.Groups
{
    public class ViewGroupModel : PageModel
    {
        [BindProperty]
        public GroupModel groupModel { get; set; }
        public ViewGroupModel()
        {

        }

        public async Task<IActionResult> OnGetAsync(string Id)
        {
            if (string.IsNullOrEmpty(Id))
            {
                return NotFound();
            }
            try
            {
                HttpClient httpClient = new HttpClient();

                //var httpResponse = await httpClient.GetAsync($"https://localhost:44366/api/group/groups/{Id}");
                var httpResponse = await httpClient
                        .GetAsync($"{CareStreamConst.Base_Url}{CareStreamConst.Base_API}{CareStreamConst.Group_By_Id_Url}{Id}");

                if (httpResponse.IsSuccessStatusCode)
                {
                    var data = await httpResponse.Content.ReadAsStringAsync();
                    groupModel = JsonConvert.DeserializeObject<GroupModel>(data);
                }
            }
            catch (System.Exception ex)
            {
                throw ex;
            }
           

            return Page();
        }
    }
}

CareStream.Web/Pages/Groups/GroupMembers/Index.cshtml
@page "{handler?}"
@model CareStream.Web.Pages.Groups.GroupMembers.IndexModel
@{
    ViewData["Title"] = "Group Members";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}


<div class="container-fluid no-gutter border-bottom">
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link pr-2" id="addMember" onclick="hideShow()" 
                       style="cursor:pointer">
                    <i class="fa fa-plus pr-2"></i>Add Member
                </a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link pr-2" href="#"><i class="fa fa-cloud-upload pr-2"></i>Import Members</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link pr-2" id="refersh" style="cursor:pointer"><i class="fa fa-refresh pr-2"></i>Refresh</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link pr-2" id="deleteMembers" style="cursor:pointer"><i class="fa fa-trash-o pr-2"></i>Remove Members</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link pr-2" href="#"><i class="fa fa-cloud-download pr-2"></i>Download Members</a>
                </li>
            </ul>
        </div>
    </nav>
</div>

@Html.AntiForgeryToken()
<div class="row">
    <input type="hidden" id="txtGroupId" value=@Model.GroupId />
    <div class="col-lg-8">
        <table class="table table-striped table-borderless table-hover table-sm table-active table-responsive-sm" style="table-layout:fixed">
            <thead>
                <tr>
                    <th>Select</th>
                    <th>Name</th>
                    <th>User Name</th>
                    <th>Department</th>
                    <th>Regions</th>
                    <th>User Type</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.groupMemberModel.AssignedMembers)
                {
                    <tr>
                        <td>
                            <input type="checkbox" name="chkboxMember-@item.Id" id="chkboxMember-@item.Id" data-memberid="@item.Id" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.GivenName)  @Html.DisplayFor(modelItem => item.Surname)
                        </td>
                        <td style="max-width:100px; word-wrap:break-word">
                            @Html.DisplayFor(modelItem => item.UserPrincipalName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Department)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Region)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.UserType)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="col-lg-4" id="addMemberDiv" style="display:none">
        <h4>Add Members</h4>
        <form asp-page-handler="AddMember" asp-route-id=@Model.GroupId  method="post">
            @foreach (var item in Model.groupMemberModel.Members)
            {
                 
                <ul>
                    <input type="checkbox" name="selectedMember" id="selectedMember" value="@item.Key" />
                    <label>@item.Value</label>
                </ul>
            }
            <input type="submit" class="btn btn-success" value="Add Member">
        </form>
    </div>

</div>

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript" language="JavaScript">
        $(document).ready(function () {

            $('#refersh').on('click', function () {
                window.location.reload();
            });

            $('#deleteMembers').on('click', function () {
                var selectedMemberIds = [];
                $("input[type='checkbox'][id^='chkboxMember']:checked").each(function () { selectedMemberIds.push($(this).data("memberid")); })

                var groupId = $('#txtGroupId').val();  
                $.ajax({
                    type: "POST",
                    url: "/groups/groupmembers?handler=GroupMemberDelete",
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader("XSRF-TOKEN",
                            $('input:hidden[name="__RequestVerificationToken"]').val());
                    },
                    data: JSON.stringify({
                        GroupId: groupId,
                        SelectedMembers:selectedMemberIds
                    }),
                    contentType: 'application/json; charset=utf-8',
                    dataType: "json",
                    cache:false,
                    success: function (response) {
                        //alert("Done");
                        window.location.reload();
                    },
                    failure: function (response) {
                        alert(response);
                    }
                })
            })
        });

        function hideShow() {
            var x = document.getElementById("addMemberDiv");
            if (x.style.display === "none") {
                x.style.display = "block";
            } else {
                x.style.display = "none";
            }
        }
    </script>

}